name: Run commitlint

on:
  push:
    branches: [ "master", "develop"]
  pull_request:
    branches: [ "master", "develop"]

jobs:
  bump-version:
    name: Bump the version
    runs-on: ubuntu-latest #self-hosted

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Automated Version Bump
      uses: phips28/gh-action-bump-version@v10.1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        minor-wording:  'add,Adds,new'
        major-wording:  'MAJOR,cut-major'
        patch-wording:  'patch,fixes'     # Providing patch-wording will override commits
                                          # defaulting to a patch bump.
        rc-wording:     'RELEASE,alpha'

