name: Version bump

on:
  pull_request:
    types:
      - closed
    branches: ["master"]

jobs:    
  bump-version:
    if: github.event.pull_request.merged == true
    name: Bump the version

    permissions:
      contents: write

    runs-on: ubuntu-latest #self-hosted

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Automated Version Bump
      uses: phips28/gh-action-bump-version@v10.1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        version-type:  'patch'
        target-branch: 'master'
        commit-message: 'CI: bumps version to {{version}} because pull request merged into master'
