name: Version bump

on:
  pull_request_target:
    types:
      - closed
    branches: [ "master"]

jobs:    
  bump-version:
    if: github.event.pull_request.merged == true
    name: Bump the version

    permissions:
      contents: write

    runs-on: ubuntu-latest #self-hosted

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Bump develop version
      uses: phips28/gh-action-bump-version@v10.1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        target-branch: 'develop'
        default:  'minor'

    - name: Bump master version
      uses: phips28/gh-action-bump-version@v10.1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        target-branch: 'master'
        default:  'minor'








